---
title: "Installing OSRM Backend"
author: "Mathew Kiang"
date: "10/8/2019"
output: html_document
---

## Introduction

This project calculates the distance between two points. We want road distance (that is, not geodesic distance), so we need to use a mapping backend such as Google Maps or OSRM. The Google Maps API limits are probably too low for what we eventually want to do (100,000 requests per month). 

This documents the process of installing [OSRM](http://project-osrm.org/) backend on a local computer (macOS) so that you can ping as many routing requests as you want. I'm documenting it for reproducibility purposes and not for educational purposes. 

In other words, this process is *specific to this project*. See [the generic instructions](https://github.com/Project-OSRM/osrm-backend) for other projects. 

## 0. Install Docker

You need [Docker](https://docs.docker.com/). Once you have Docker installed, the rest of this should work regardless of OS (but has only been tested on macOS). 

## 1. Install the Docker image

Once Docker is running, use `docker pull osrm/osrm-backend` in the terminal to pull the OSRM backend. [Source.](https://hub.docker.com/r/osrm/osrm-backend/)

## 2. Download the OSM data files

We need the OSM data files for North America. Download them from [geofabrik](http://download.geofabrik.de/north-america.html). Due to the size of the file, I downloaded each state separately and then merged them together using [`osmium-merge`](https://docs.osmcode.org/osmium/latest/osmium-merge.html).

## 3. Extract the OSM data file

Run this in the terminal (in the same directory as the OSM data file): `docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/merged_us.osm.pbf`

## 4. Pre-process the OSM data file

Run `docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/merged_us.osrm` in the terminal.

Then `docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-customize /data/merged_us.osrm` in the terminal. 

## 5. Run the server
`docker run -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/merged_us.osrm`

## 6. Set up the server in R
**In `R`**, run these commands to connect `R` to the Docker server. 
`options(osrm.server = "http://0.0.0.0:5000/", osrm.profile = "driving")`

## Console output
```
mvk$ docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/merged_us.osm.pbf
[info] Parsed 0 location-dependent features with 0 GeoJSON polygons
[info] Using script /opt/car.lua
[info] Input file: merged_us.osm.pbf
[info] Profile: car.lua
[info] Threads: 8
[info] Parsing in progress..
[info] input file generated by osmium/1.10.0
[info] timestamp: n/a
[info] Using profile api version 4
[info] Found 3 turn restriction tags:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Parsing finished after 568.611 seconds
[info] Raw input contains 765928221 nodes, 67882301 ways, and 72549 relations, 205039 restrictions
[info] Sorting used nodes        ... ok, after 1.9107s
[info] Erasing duplicate nodes   ... ok, after 0.386757s
[info] Sorting all nodes         ... ok, after 0.398341s
[info] Building node id map      ... ok, after 0.92647s
[info] Confirming/Writing used nodes     ... ok, after 258.907s
[info] Writing barrier nodes     ... ok, after 0s
[info] Writing traffic light nodes     ... ok, after 0s
[info] Processed 194956476 nodes
[info] Sorting edges by start    ... ok, after 10.5711s
[info] Setting start coords      ... ok, after 9.35122s
[info] Sorting edges by target   ... ok, after 10.252s
[info] Computing edge weights    ... ok, after 32.8807s
[info] Sorting edges by renumbered start ... ok, after 10.3459s
[info] Writing used edges       ... ok, after 38.4384s -- Processed 205365952 edges
[info] Writing way meta-data     ... ok, after 0.920241s -- Metadata contains << 21591049 entries.
[info] Sorting used ways         ... ok, after 0.028586s
[info] Collecting start/end information on 22 maneuver overrides...ok, after 0.302377s
[info] Collecting start/end information on 22 maneuver overrides...ok, after 0.000113s
[info] Collecting start/end information on 205039 restrictions...ok, after 1.80616s
[info] Collecting start/end information on 205039 restrictions...ok, after 0.210356s
[info] writing street name index ... ok, after 0.339268s
[info] extraction finished after 950.144s
[info] Generating edge-expanded graph representation
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.187201
[info] Edge compression ratio: 0.227262
[info]  graph compression removed 19156155 annotations of 21591049 in 54.9542 seconds
[info] Find segregated edges in node-based graph ...
[info] ok, after 128.312s
[info] Segregated edges count = 819547
[info] Writing nodes for nodes-based and edges-based graphs ...
[info] Geometry successfully removed:
  compressed edges: 93206300
  compressed geometries: 410208688
  longest chain length: 6987
  cmpr ratio: 0.227217
  avg chain length: 4.40108
[info] Generating edge expanded nodes ... 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Expanding via-way turn restrictions ... 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Generated 89413816 nodes (14864 of which are duplicates)  and 205063455 segments in edge-expanded graph
[info] Generating edge-expanded edges 
[info] [info] Using profile api version 4
[info] Using profile api version 4
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 7935200, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.764659&mlon=-122.169652
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 7935200, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.764659&mlon=-122.169652
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 7935200, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.764659&mlon=-122.169652
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 7935254, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.764659&mlon=-122.169652
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 7935254, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.764659&mlon=-122.169652
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 7935254, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.764659&mlon=-122.169652
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 15811500, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=34.32211&mlon=-83.410483
 10% . 20% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 42684382, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=32.533973&mlon=-81.013553
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 48393223, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.17513&mlon=-95.425205
. 30% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 61981962, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=34.925952&mlon=-98.098521
. 40% .[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 96907038, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=34.940718&mlon=-80.666954
 50% .[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 108747841, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=43.17285&mlon=-75.175466
 60% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 127527842, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.0637&mlon=-74.829094
. 70% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 141255823, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=39.773634&mlon=-86.153309
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 144554801, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=41.884403&mlon=-87.621391
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 151179365, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.111822&mlon=-122.011241
 80% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 161581757, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=33.742916&mlon=-118.287885
[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 161751565, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=37.476644&mlon=-105.857552
. 90% [warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 179540048, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=47.062794&mlon=-122.918649
.[warn] Turn is a u turn but not turning to the first connected edge of the intersection. Node ID: 193891869, OSM link: http://www.openstreetmap.org/?zoom=18&mlat=40.291542&mlon=-83.068382

[info] Sorting and writing 22 maneuver overrides...
[info] done.
[info] Renumbering turns
[info] Writing 0 conditional turn penalties...
[info] Generated 205063455 edge based node segments
[info] Node-based graph contains 88661897 edges
[info] Edge-expanded graph ...
[info]   contains 174826843 edges
[info] Timing statistics for edge-expanded graph:
[info] Renumbering edges: 2.39188s
[info] Generating nodes: 48.8441s
[info] Generating edges: 588.488s
[info] Generating guidance turns 
[info] . 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% .
[info] done.
[info] Created 216 entry classes and 79779 Bearing Classes
[info] Handled: 312648 of 535634 lanes: 58.3697 %.
[info] Assigned 197537753 turn instruction types:
[info]   new name: 4850217 (2.46%)
[info]   continue: 10774476 (5.45%)
[info]   turn: 79670599 (40.33%)
[info]   merge: 92269 (0.05%)
[info]   on ramp: 154603 (0.08%)
[info]   off ramp: 110714 (0.06%)
[info]   fork: 949027 (0.48%)
[info]   end of road: 33882541 (17.15%)
[info]   notification: 812 (0.00%)
[info]   enter roundabout: 39315 (0.02%)
[info]   enter and exit roundabout: 2633 (0.00%)
[info]   enter rotary: 2051 (0.00%)
[info]   enter and exit rotary: 163 (0.00%)
[info]   enter roundabout turn: 16890 (0.01%)
[info]   enter and exit roundabout turn: 25 (0.00%)
[info]   (noturn): 18363894 (9.30%)
[info]   (suppressed): 48338099 (24.47%)
[info]   roundabout: 2655 (0.00%)
[info]   exit roundabout: 47757 (0.02%)
[info]   rotary: 177 (0.00%)
[info]   exit rotary: 2444 (0.00%)
[info]   roundabout turn: 20 (0.00%)
[info]   exit roundabout turn: 17090 (0.01%)
[info]   (stay on roundabout): 63395 (0.03%)
[info]   (sliproad): 155887 (0.08%)
[info] Assigned 197537753 turn instruction modifiers:
[info]   uturn: 8866322 (4.49%)
[info]   sharp right: 2703979 (1.37%)
[info]   right: 55656373 (28.18%)
[info]   slight right: 4130913 (2.09%)
[info]   straight: 64220580 (32.51%)
[info]   slight left: 4029834 (2.04%)
[info]   left: 54960988 (27.82%)
[info]   sharp left: 2968764 (1.50%)
[info] Guidance turn annotations took 270.762s
[info] Writing Intersection Classification Data
[info] ok, after 6.92052s
[info] Writing Turns and Lane Data...
[info] ok, after 10.3529s
[info] Saving edge-based node weights to file.
[info] Done writing. (9.97547)
[info] Computing strictly connected components ...
[info] Found 110287 SCC (14 large, 110273 small)
[info] SCC run took: 6.93591s
[info] Building r-tree ...
[info] Constructing r-tree of 205063455 segments build on-top of 194956476 coordinates
[info] finished r-tree construction in 62.3547 seconds
[info] Writing edge-based-graph edges       ... 
[info] ok, after 386.667s
[info] Processed 174826843 edges
[info] Expansion: 117221 nodes/sec and 53761 edges/sec
[info] To prepare the data for routing, run: ./osrm-contract "/data/merged_us.osrm"
[info] RAM: peak bytes used: 56466481152

mvk$ docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/merged_us.osrm
[info] Computing recursive bisection
[info] Loaded compressed node based graph: 93206218 edges, 194956476 nodes
[info]  running partition: 128 1.2 0.25 10 1000 # max_cell_size balance boundary cuts small_component_size
[info] Found 158541342 SCC (5 large, 158541337 small)
[info] SCC run took: 8.24832s
[info] Full bisection done in 2506.43s
[info] Loaded node based graph to edge based graph mapping
[info] Loaded edge based graph for mapping partition ids: 349527862 edges, 89413816 nodes
[info] Fixed 22624 unconnected nodes
[info] Edge-based-graph annotation:
[info]   level 1 #cells 431510 bit size 19
[info]   level 2 #cells 33250 bit size 16
[info]   level 3 #cells 2076 bit size 12
[info]   level 4 #cells 68 bit size 7
[info] Renumbered data in 444.362 seconds
[info] MultiLevelPartition constructed in 23.5523 seconds
[info] CellStorage constructed in 6.15919 seconds
[info] MLD data writing took 41.6156 seconds
[info] Cells statistics per level
[info] Level 1 #cells 431510 #boundary nodes 8883165, sources: avg. 13, destinations: avg. 19, entries: 165161849 (1321294792 bytes)
[info] Level 2 #cells 33250 #boundary nodes 1626309, sources: avg. 33, destinations: avg. 46, entries: 67265679 (538125432 bytes)
[info] Level 3 #cells 2076 #boundary nodes 250534, sources: avg. 81, destinations: avg. 110, entries: 24928510 (199428080 bytes)
[info] Level 4 #cells 68 #boundary nodes 18968, sources: avg. 187, destinations: avg. 250, entries: 4480597 (35844776 bytes)
[info] Bisection took 3175.59 seconds.
[info] RAM: peak bytes used: 29968535552

mvk$ docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-customize /data/merged_us.osrm
[info] Loaded edge based graph: 349527862 edges, 89413816 nodes
[info] Loading partition data took 86.7633 seconds
[info] Cells customization took 189.577 seconds
[info] Cells statistics per level
[info] Level 1 #cells 431510 #boundary nodes 8883165, sources: avg. 13, destinations: avg. 19, entries: 165161849 (1321294792 bytes)
[info] Level 2 #cells 33250 #boundary nodes 1626309, sources: avg. 33, destinations: avg. 46, entries: 67265679 (538125432 bytes)
[info] Level 3 #cells 2076 #boundary nodes 250534, sources: avg. 81, destinations: avg. 110, entries: 24928510 (199428080 bytes)
[info] Level 4 #cells 68 #boundary nodes 18968, sources: avg. 187, destinations: avg. 250, entries: 4480597 (35844776 bytes)
[info] Unreachable nodes statistics per level
[warn] Level 1 unreachable boundary nodes per cell: 0.000210887 sources, 0.000368473 destinations
[warn] Level 2 unreachable boundary nodes per cell: 0.00087218 sources, 0.00123308 destinations
[warn] Level 3 unreachable boundary nodes per cell: 0.00289017 sources, 0.00722543 destinations
[warn] Level 4 unreachable boundary nodes per cell: 0.0147059 sources, 0.191176 destinations
[info] Unreachable nodes statistics per level
[warn] Level 1 unreachable boundary nodes per cell: 0.0124169 sources, 0.00917476 destinations
[warn] Level 2 unreachable boundary nodes per cell: 0.0949474 sources, 0.0665865 destinations
[warn] Level 3 unreachable boundary nodes per cell: 0.557803 sources, 0.411368 destinations
[warn] Level 4 unreachable boundary nodes per cell: 2.04412 sources, 2.11765 destinations
[info] Unreachable nodes statistics per level
[warn] Level 1 unreachable boundary nodes per cell: 0.209506 sources, 0.136799 destinations
[warn] Level 2 unreachable boundary nodes per cell: 1.38081 sources, 0.858586 destinations
[warn] Level 3 unreachable boundary nodes per cell: 5.84152 sources, 3.58574 destinations
[warn] Level 4 unreachable boundary nodes per cell: 19.8088 sources, 12.8676 destinations
[info] Unreachable nodes statistics per level
[warn] Level 1 unreachable boundary nodes per cell: 0.000530695 sources, 0.000959422 destinations
[warn] Level 2 unreachable boundary nodes per cell: 0.00366917 sources, 0.00556391 destinations
[warn] Level 3 unreachable boundary nodes per cell: 0.0250482 sources, 0.0366089 destinations
[warn] Level 4 unreachable boundary nodes per cell: 0.279412 sources, 0.529412 destinations
[info] MLD customization writing took 82.9556 seconds
[info] Graph writing took 49.2468 seconds
[info] RAM: peak bytes used: 35558547456
```
